spring:
  docker:
    compose:
      lifecycle-management: start-and-stop
      enabled: true
  application:
    name: 'Development Books'

  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/devbooks
    hikari:
      username: devbooks
      password: devbooks-local
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080