name: Build and Test Spring Boot App (PR)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: 'maven'

      - name: Build with Maven Wrapper
        run: ./mvnw clean package -DskipTests -U

      - name: Run Tests
        run: ./mvnw test
